server:
  port: 8888
  shutdown: "graceful"

management:
  endpoint:
    health:
      show-details: "never"
    prometheus:
      access: read_only
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, prometheus

springdoc:
  packagesToScan: uk.gov.moj.cp.controllers
  writer-with-order-by-keys: true

logging:
  level:
    uk.gov.moj.cp: ${LOGGING_LEVEL:INFO}

spring:
  application:
    name: stg-vsp-subscription

notifications:
  gov-notify-api-key: ${GOV_NOTIFY_API_KEY:xx}
  user-logged-in-email-template-id: ${TMC_USER_LOGGED_IN_TEMPLATE_ID:xx}
  service-url: ${TMC_SERVICE_URL:https://track-my-case-dev.apps.live.cloud-platform.service.justice.gov.uk}
  target-email: ${TMC_TARGET_EMAIL:xx}
